---

resources_kubeconfig_local_path: '{{ ansible_user_dir }}/.kube/config'

resources_definition: []
  # - name: calico
  #   resource_definition: '{{ lookup("template", "cni/calico/3.26/config.j2") | from_yaml }}'
  # - name: cilium
  #   template: cni/cilium/1.16/config.j2
  # - name: ceph
  #   src: cni/cilium/1.16/config.yml
  # - name: web
  #   resource_definition:
  #     apiVersion: v1
  #     kind: Service
  #     metadata:
  #       name: web
  #       namespace: testing
  #       labels:
  #         app: galaxy
  #         service: web
  #     spec:
  #       selector:
  #         app: galaxy
  #         service: web
  #       ports:
  #       - protocol: TCP
  #         targetPort: 8000
  #         name: port-8000-tcp
  #         port: 8000
