---

galaxy_info:
  author: flyoverhead
  description: K3S service deployment and management
  license: GNU
  min_ansible_version: '2.15'
  galaxy_tags:
    - k3s
  platforms:
    - name: Debian
      versions:
        - bookworm

dependencies:
  - role: resources
