---

galaxy_info:
  role_name: patches
  namespace: flyoverhead
  author: flyoverhead
  description: JSON patch application against k3s cluster resources
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - kubernetes
    - patches

dependencies: []
