---

- name: install | resources
  kubernetes.core.k8s:
    apply: '{{ item.apply | default(omit) }}'
    delete_all: '{{ item.delete_all | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    name: '{{ item.name | default(omit) }}'
    resource_definition: '{{ item.resource_definition | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    state: '{{ item.state | default("present") }}'
    template: '{{ item.template | default(omit) }}'
    wait: '{{ item.wait | default(true) }}'
    kubeconfig: '{{ resources_kubeconfig_local_path }}'
    validate_certs: false
  loop: '{{ resources_definition }}'
  loop_control:
    label: '{{ item.name }}'
