---

k3s_version: v1.31.3+k3s1 # https://github.com/k3s-io/k3s/releases

k3s_group: k3s
k3s_server_group: '{{ k3s_group }}_server'
k3s_agent_group: '{{ k3s_group }}_agent'

k3s_config:
  iface: eth0
  api_port: 6443
  cluster_cidr: 10.52.0.0/16
  lb_ip_range: 192.168.1.150-192.168.1.160

k3s_kube_vip_config:
  version: v0.8.7 # https://github.com/kube-vip/kube-vip/releases
  api_address: 192.168.1.250
  iface: '{{ k3s_config.iface }}'
  lb_ip_range: '{{ k3s_config.lb_ip_range }}'

k3s_cilium_config:
  repo: https://helm.cilium.io
  version: v1.16.4  # https://github.com/cilium/cilium/releases
  iface: '{{ k3s_config.iface }}' # auto
  lb_ip_range: '{{ k3s_config.lb_ip_range }}'

k3s_controller_config:
  address: localhost
  path: "{{ lookup('env', 'HOME') }}/.kube"
  name: config
  owner: "{{ lookup('env', 'USER') }}"
  group: staff

k3s_uninstall: false
