---

galaxy_info:
  role_name: helm
  namespace: flyoverhead
  author: flyoverhead
  description: Helm chart deployment against a k3s cluster
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - helm
    - kubernetes

dependencies: []
